apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-personsapi
  name: udaconnect-personsapi
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 5000
      nodePort: 30004
  selector:
    service: udaconnect-personsapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-personsapi
  name: udaconnect-personsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-personsapi
  template:
    metadata:
      labels:
        service: udaconnect-personsapi
    spec:
      containers:
        - image: mmansoornano/udacity-udaconnect-person_api:latest
          name: udaconnect-personsapi
          imagePullPolicy: "IfNotPresent"
      #     env:
      #       - name: DB_USERNAME
      #         valueFrom:
      #           configMapKeyRef:
      #             name: db-env
      #             key: DB_USERNAME
      #       - name: DB_PASSWORD
      #         valueFrom:
      #           secretKeyRef:
      #             name: db-secret
      #             key: DB_PASSWORD
      #       - name: DB_NAME
      #         valueFrom:
      #           configMapKeyRef:
      #             name: db-env
      #             key: DB_NAME
      #       - name: DB_HOST
      #         valueFrom:
      #           configMapKeyRef:
      #             name: db-env
      #             key: DB_HOST
      #       - name: DB_PORT
      #         valueFrom:
      #           configMapKeyRef:
      #             name: db-env
      #             key: DB_PORT
      # restartPolicy: Always