apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connectionsapi
  name: udaconnect-connectionsapi
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5000
      nodePort: 30002
  selector:
    service: udaconnect-connectionsapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connectionsapi
  name: udaconnect-connectionsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connectionsapi
  template:
    metadata:
      labels:
        service: udaconnect-connectionsapi
    spec:
      containers:
        - image: mmansoornano/udacity-udaconnect-connection_api:latest
          name: udaconnect-connectionsapi
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always